### PR TITLE
Ability to automatically stop timer when issue status was changed

### PR DESCRIPTION
**Pull request by corlinus**
I've implemented new ability, which allows to stop timer automatically when issue status changed from given to another given value. It works when status changes by user directly as well as by commit message keywords.

### CODE REVIEW

**Comment by delaitre** [comment]
Hi,

The code looks good. However, I have a question. You say this patch allows to stop automatically the current time tracker if the status of the tracked issue change (either manually or by a commit message). However, the settings you've added seems confusing as it says "Issue status transition to apply when a time tracker is stopped". Does this means you've implemented another feature which is "change the status from a to b when a time tracker is stopped" ?

I did not try the patch yet, I've just overview the code, but am I missing something ?

**Comment by corlinus** [comment]
Hi,

Now I see that this setting must be called "Stop timer when issue status applies transition" or something like this. It sets transitions with which timer have to stop.

Must I fix it or you'll do? Actually my English is not very well to write such messages.

**Comment by delaitre** [comment]
I can do it, but I don't know when I'll have time to work on the plugin.

**Comment by corlinus** [comment]
So what i have to do?

Did I closed requiest. It's first time I work with github pull requiests.

**Comment by delaitre** [comment]
No, I'll close it when the merge will be done. You have nothing to do :)

Thanks for the contribution.

**Comment by corlinus** [comment]
Ок. Thank you (:

**Pull request closed without merging**
