### PR TITLE
Time Tracker popup extension

### PR DESCRIPTION
**Pull request by pulse00**
Hi,

i've extended your time tracking plugin with a popup time-tracker.

The features are:
- Open a time tracker popup
- Start/Stop timers from the popup
- Switch Project/Issue in popup to track time for different issue
- Search for issues via autocompletion
- Add time entries (including activities and comment) directly in the popup

I'm new to ruby/rails programming, so if you're interested in the extension, you might pull it into a separate branch, as i strongly suggest that the code of the extension should be reviewed by someone with more experience before merging it into master.

### CODE REVIEW

**Comment by delaitre** [comment]
Thanks a lot for the patch. I've not tested it yet but I will as soon as time permits.

**Comment by delaitre** [comment]
I've tried to test this feature without success. A quick look at the source seems to indicate that a link in the account menu allows to open the popup, but nothing appears here (tried with an old redmine 1.0.2). I've found nothing to open the popup.

Could you explain me what should I see?

Another problem I saw is that your patch set is relatively big and I have no much time to maintain the plugin. Thus, including your work could be difficult for me to maintain it afterward.

This is my current though, however as I can't test the feature (I'm not sure what it really does) I can't take a final decision.

Bonus: rebasing your work on the current master will be a plus

**Comment by that0n3guy** [comment]
I just tested this.  It does work but needs to be updated.  Here is a screenshot with some explanation text: 

http://img560.imageshack.us/i/redminetimetrackerpopou.png/

**Comment by delaitre** [comment]
Ok, I see what is this now...however I don't understand why it's really useful?
Does the main feature is to be able to select multiple issue to work on and then start/stop the time tracking on them easily?
If this is the case, it should/will be implemented in the "time tracker lists page of the last plugin version.

**Comment by that0n3guy** [comment]
I don't know if you can work on multiple issues, I didnt test that.  The only thing its really useful for is that you don't have to leave the page your on in redmine, which is nice.  I got rid of it though because I like the new version w/ the play/pause/stop buttons.

I'd rather have the "not running" text be a link that does something similar but with a jquery/modalframe popup.  That way you still don't have to leave the page your on (like a wiki page, or forum) to start working on an issue.

**Comment by delaitre** [comment]
Ok, I got it!

I'm often in the same situation and here is how I manage to start a time
tracker in this situation:
- I'm on a wiki page for example
- I want to start the time tracker for an issue but don't want to loose the
  current wiki page
- I middle-click the roadmap or issue list to open it in a new tab
- I search my issue by browsing the roadmap/issue list or I make a search
  with the redmine search box
- I start the time tracker
- I close the tab
- I'm back in the wiki page with the time tracker started (which will appear
  in the current tab as soon as the refresh period is elapsed)

I think this is not too cumbersome to do it that way. Moreover, as you no
more use your extension, I'll not merge it. This is too much work to
maintain.

Thanks again for the work you've done.

**Comment by that0n3guy** [comment]
Thats the way I handle it as well.  After a while I find myself with 10 tabs open though :).  But thats probably a personal issue, ha.

Oh, and I'm not the creator of that extension.  I'm just a random tester.  But I probably wouldn't merge it as well unless the author has some other significant changes to the extension.

**Comment by pulse00** [comment]
Sorry for not answering so long, i had a lot to of work to do in the last few weeks. I can understand that it's too much work for you to maintain the patch. As i'm not sure if i have the time to keep maintaining the extension in the future, it'll probably be better that way.

**Pull request closed without merging**
